version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t package/
  build:
    commands:
      - echo "Packaging Lambda function..."
      - cp lambda_function.py package/
      - cd package
      - zip -r ../lambda_function.zip .
artifacts:
  files:
    - lambda_function.zip
